trigger: none   
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    clean: true

  - script: echo "✅ Code pulled successfully from GitHub repository."
    displayName: "Pull latest code"