export const REST = {
  patient: '/openmrs/ws/rest/v1/patient',
  visit: '/openmrs/ws/rest/v1/visit',
  visitType: '/openmrs/ws/rest/v1/visittype',
  visitLocation: '/openmrs/ws/rest/v1/bahmnicore/visitLocation',
  visitEnd: '/openmrs/ws/rest/v1/bahmnicore/visit/endVisit',
  visitDocumentUpload: '/openmrs/ws/rest/v1/bahmnicore/visitDocument/uploadDocument',
  encounter: '/openmrs/ws/rest/v1/encounter',
  location: '/openmrs/ws/rest/v1/location',
  session: '/openmrs/ws/rest/v1/session',
  provider: '/openmrs/ws/rest/v1/provider',
  bahmnicorePatient: '/openmrs/ws/rest/v1/bahmnicore/patient',
  appointment: '/openmrs/ws/rest/v1/appointment',
  recurringAppointments: '/openmrs/ws/rest/v1/recurring-appointments',
  appointmentService: '/openmrs/ws/rest/v1/appointmentService',
  bahmniProgramEnrollment: '/openmrs/ws/rest/v1/bahmniprogramenrollment',
  concept: '/openmrs/ws/rest/v1/concept',
  idgenIdentifierSource: '/openmrs/ws/rest/v1/idgen/identifiersource',
} as const;

export const FHIR = {
  patient: '/openmrs/ws/fhir2/R4/Patient',
  encounter: '/openmrs/ws/fhir2/R4/Encounter',
  serviceRequest: '/openmrs/ws/fhir2/R4/ServiceRequest',
  diagnosticReport: '/openmrs/ws/fhir2/R4/DiagnosticReport',
  submitBundle: '/openmrs/ws/fhir2/R4/DiagnosticReport/$submit-bundle',
  allergyIntolerance: '/openmrs/ws/fhir2/R4/AllergyIntolerance',
  condition: '/openmrs/ws/fhir2/R4/Condition',
  medicationRequest: '/openmrs/ws/fhir2/R4/MedicationRequest',
  observation: '/openmrs/ws/fhir2/R4/Observation',
  consultationBundle: '/openmrs/ws/fhir2/R4/ConsultationBundle',
  valueSet: '/openmrs/ws/fhir2/R4/ValueSet',
  documentReference: '/openmrs/ws/fhir2/R4/DocumentReference',
  appointment: '/openmrs/ws/fhir2/R4/Appointment',
} as const;
